### ISSUE TITLE
Creating stats files from more modern sequencer technologies

### ISSUE THREAD

**Issue by rickymagner** [mlinderm/npsv2#1]
Hi, I was curious in trying out your tool with some data from some more modern sequencers. I was reading the [section](https://github.com/mlinderm/npsv2?tab=readme-ov-file#preprocessing-to-create-a-stats-file) on genotyping, and saw the sequencer argument only seems to support some older technologies. The ART dependency seems to not have had a release for around 8 years or so. Is there any way to run the tool on reads from NovaSeq 6000, or even NovaSeq X? Are there plans to update this dependency to allow for more modern types of technology?

Thanks!

**Comment by mlinderm** [comment]
Thanks for checking out the tool! Unfortunately ART has not been updated with new machines. That said, the sequencer model seems to play relatively little role in the simulation (to my understanding, it is used for simulating base errors). My approach is to use the most recent model with the corresponding read length. For example, for the [NYGC 1000 Genomes](https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/36055201/) data from a NovaSeq 6000 I used `HSXn` "HiSeqX PCR free (150bp)". I will update the README with that note.

**Comment by rickymagner** [comment]
That sounds like a good idea. A note in the README would definitely help. I'll try out the HSXn stats and see how it goes. Thanks!
